platform :ios , '8.0'

pod 'AFNetworking', '~> 3.1.0'
pod 'MJExtension', '~> 3.0.10'
pod 'MJRefresh', '~> 3.1.0'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'MBProgressHUDExtensions', '~> 0.0.1'
pod 'SDWebImage', '~> 3.7.6'
pod 'IQKeyboardManager', '~> 4.0.2'
pod 'ZXingObjC', '~> 3.1.0'
pod 'Masonry', '~> 1.0.1'





